name: Python package on macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 15 * * *

env:
  PYTHON: python3.10

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install requirements on macOSX
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install python@3.10 graphicsmagick boost-python3
        HOMEBREW_NO_AUTO_UPDATE=1 brew link --overwrite python@3.10
        HOMEBREW_NO_AUTO_UPDATE=1 brew link --overwrite boost-python3
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 setup.py install
    - name: Test
      run: |
        make test
